### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by ljvmiranda921**
@ardieorden I rebased some commits so now we're working on the latest change in `master` (this already has the `SpellBook` and the three spells). I suggest deleting your local branch na lang and "re-track" whatever is here

### CODE REVIEW

**Comment by ljvmiranda921** [comment]
@ardieorden  update. The API Documentation is all good, I've done most parts na. I'll just do the polishing. I suggest you work on the "General" tab:
- Features
- Installation
- Basic Usage

Similar to the README, just put it in RST.

Tomorrow I'll work on CONTRIBUTING and Data Warehouse Setup. Maybe you can help me out in the latter too.

**Comment by ardieorden** [comment]
@ljvmiranda921 Got it! For now, I'll focus on getting all of the sections in the "General" tab done by this weekend. After I'm through with the 3 sections, I'll help you out as well with the Contributing and Data Warehouse Setup sections.

**Comment by ardieorden** [comment]
I'm done with the Installation/Setup and Usage pages. I notice you've also finished writing the Features page. Thanks @ljvmiranda921 ! Right now, I'm just proofreading the [docs website](https://geomancer.readthedocs.io/en/add-docs) and checking if there's anything we missed.

**Comment by ljvmiranda921** [comment]
Ok thank you @ardieorden ! Tell me if you're done, I'm done with my part na. 
I'll do a rebase so that our commits are clean then merge this to master

**Comment by ardieorden** [comment]
I'm done! Everything looks good to me

**Review by ardieorden — APPROVED** [review]

**Pull request merged**
